PACKAGE_NAME="kvm-hypercall-patch"
PACKAGE_VERSION="1.0"

BUILT_MODULE_NAME[0]="kvm-hypercall-patch"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
AUTOINSTALL=yes

MAKE[0]="make KERNEL_VERSION=${kernelver}"
